Crash report: 
Exception: [Errno 2] No such file or directory: 'version.txt'
Traceback: 
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/app.py", line 864, in <module>
    run_with_crash_writing("MaestroApp", main)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/scheduleLib/crash_reports.py", line 36, in run_with_crash_writing
    raise e
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/scheduleLib/crash_reports.py", line 33, in run_with_crash_writing
    function(*args, **kwargs)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/app.py", line 856, in main
    window = MainWindow()
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/app.py", line 150, in __init__
    with open("version.txt", "r") as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^
